spring:
  application:
    name: CAR-SERVICE
  servlet:
    multipart:
      enabled: true
      max-file-size: 500KB
      max-request-size: 500KB        
server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
