spring:
  application:
    name: LOGIN-SERVICE
    
server:
  port: 8086
 
security:
  oauth2:
    client:
      client-id: 271935640663918
      client-secret: 3cdbf823fd5fa4d1b5a2cf7ef5701081
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost